### ISSUE TITLE
Test the name of the scenario folder

### ISSUE THREAD

**Issue by leo-desbureaux-tellae** [tellae/starling#19]
**Problem exposition**

Scenario can be created manually or by doing a copy of an existing scenario and adding small modifications.

In the second case, the modeler may forget to change the scenario name in the parameters file.

This can lead to simulation problem and even overwriting the outputs of the original scenario.

**Proposed solution**

Check that the scenario folder has the same name than the scenario name specified in the parameters file when reading the parameters file. Raise an error if it is not the case.

**Comment by vincent-leblond** [comment]
In MATSIM, by default an existing output directory can't be overwritten by a simulation. A parameter must be switched off to allow this. It could be another interesting and complementary idea.
